# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'EFRS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EFRS
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Messaging', '~> 5.11.0'
  pod 'Fabric', '~> 1.7.5'

end
