# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
min_fastlane_version("2.70.1")

default_platform(:ios)

platform :ios do
  before_all do
    ensure_git_status_clean
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # sync_code_signing(type: "appstore") # more information: https://codesigning.guide
    build_app(scheme: "eFRS") # more options available
    upload_to_testflight(
        distribute_external: true,
        demo_account_required: true,
        reject_build_waiting_for_review: true,
        changelog: "Scheduled Tasks
                    Translations
                    Removed menu from form view
                    More text options (Bold, Italic, Alignment & Size)
                    Add from Photo Gallery / Camera Roll
                    Minor improvements"
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

end


# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics
